// <auto-generated />
using System;
using Actionlogger.ActionService.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actionlogger.ActionService.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220530213132_meetings")]
    partial class meetings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Actionlogger.Core.Entity.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DueDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResponsibleProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Actionlogger.Core.Entity.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Creator")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Actionlogger.Core.Entity.MeetingMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingMembers");
                });

            modelBuilder.Entity("Actionlogger.Core.Entity.Action", b =>
                {
                    b.HasOne("Actionlogger.Core.Entity.Meeting", null)
                        .WithMany("Actions")
                        .HasForeignKey("MeetingId");
                });

            modelBuilder.Entity("Actionlogger.Core.Entity.MeetingMember", b =>
                {
                    b.HasOne("Actionlogger.Core.Entity.Meeting", null)
                        .WithMany("Members")
                        .HasForeignKey("MeetingId");
                });

            modelBuilder.Entity("Actionlogger.Core.Entity.Meeting", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
